### PR TITLE
Fix `no_route` on macos

### LINKED ISSUE #63: Bug/Test failure on MacBook
On Macbook Air 2020 with MacOS `12.3.1`, I got the following error when running `check.sh` and `run_ci_tests.sh`:

```
failures:

---- no_route stdout ----
Custom { kind: ConnectionAborted, error: "connect to host 255.255.255.255 port 22: Address family not supp
orted by protocol family" }
thread 'no_route' panicked at 'assertion failed: `(left == right)`
  left: `ConnectionAborted`,
 right: `Other`', tests/openssh.rs:676:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    no_route
```

The test in question is [`no_route`](https://github.com/openssh-rust/openssh/blob/729fe31bc184e5d352a752d79b4233bfbf872c17/tests/openssh.rs#L676).

The error is created using [`Error::interpret_ssh_error`](https://github.com/openssh-rust/openssh/blob/729fe31bc184e5d352a752d79b4233bfbf872c17/src/error.rs#L152).

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #63 using "192.0.2.1" plus timeout of 0ns.

The only drawback is that now `no_route` takes much longer to run.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/openssh-rust/openssh/67)

File: tests/openssh.rs [hunk 1]
```diff
@@ -669,11 +671,15 @@ async fn cannot_resolve() {
 
 #[tokio::test]
 async fn no_route() {
-    for err in connects_err("255.255.255.255").await {
+    let mut builder = SessionBuilder::default();
+
+    builder.connect_timeout(Duration::from_nanos(0));
```
Comment (jonhoo) [inline tests/openssh.rs:676]: I _think_ a duration of 0s is actually "special" and means basically no timeout. I think you may have more luck setting this to something like 1.

File: .github/workflows/os-check.yml [hunk 2]
```diff
@@ -32,5 +32,5 @@ jobs:
       - name: cargo check
         uses: actions-rs/cargo@v1
         with:
-          command: check
+          command: test
```
Comment (jonhoo) [inline .github/workflows/os-check.yml:35]: This doesn't seem right — this was intentionally `check` as the name of the job implies.

**Review by jonhoo — CHANGES_REQUESTED** [review]

File: .github/workflows/os-check.yml (hunk 2 above)
Comment (NobodyXu) [reply .github/workflows/os-check.yml:35]: Right, l will change the name of the job to match what it does then.

IMO it is necessary to run cargo-test on the github action so that it doesn't accidentally break on MacOS.

File: tests/openssh.rs (hunk 1 above)
Comment (NobodyXu) [reply tests/openssh.rs]: Done!

File: .github/workflows/os-check.yml (hunk 2 above)
Comment (NobodyXu) [reply .github/workflows/os-check.yml:35]: Done!

**Review by jonhoo — APPROVED** [review]
I'm happy with this without the caching change :+1:

File: .github/workflows/os-check.yml [hunk 3]
```diff
@@ -29,8 +29,21 @@ jobs:
...
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-os-check-v0
+      - name: cargo test
+        uses: actions-rs/cargo@v1
```
[the remark this answers is not in the document]
Comment (NobodyXu) [reply .github/workflows/os-check.yml]: Done!

File: .github/workflows/os-check.yml (hunk 2 above)
Comment (NobodyXu) [reply .github/workflows/os-check.yml:39]: Actually I've been developing on MacBook Air 2020 for some time and it's been working quite good.
With Docker Desktop, I can run all the integration tests without any problem.

Comment (jonhoo) [reply .github/workflows/os-check.yml:39]: Right, but that doesn't work on GitHub actions

File: .github/workflows/os-check.yml [hunk 4]
```diff
@@ -29,8 +29,12 @@ jobs:
           profile: minimal
           toolchain: stable
       - uses: actions/checkout@v2
-      - name: cargo check
+      - name: Create Cargo.lock
         uses: actions-rs/cargo@v1
         with:
-          command: check
+          command: update
```
Comment (jonhoo) [inline .github/workflows/os-check.yml:35]: I don't think this explicit update step is needed?

Comment (NobodyXu) [reply .github/workflows/os-check.yml:35]: Nope, I forgot to remove it .

It's part of the code required for caching.

Comment (NobodyXu) [reply .github/workflows/os-check.yml:35]: I will open another PR to fix it.

Looks like I need to slow down a bit to ensure quality of the PR/code.

Comment (NobodyXu) [reply .github/workflows/os-check.yml:35]: Done!
#74 shall fix this.
